# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnSistemaActividad.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_vtnSistemaActividad(object):
    def setupUi(self, vtnSistemaActividad):
        if not vtnSistemaActividad.objectName():
            vtnSistemaActividad.setObjectName(u"vtnSistemaActividad")
        vtnSistemaActividad.resize(609, 600)
        self.centralwidget = QWidget(vtnSistemaActividad)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 10, 351, 41))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.lblNombre = QLabel(self.centralwidget)
        self.lblNombre.setObjectName(u"lblNombre")
        self.lblNombre.setGeometry(QRect(70, 120, 61, 16))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.lblNombre.setFont(font1)
        self.lblCedula = QLabel(self.centralwidget)
        self.lblCedula.setObjectName(u"lblCedula")
        self.lblCedula.setGeometry(QRect(70, 160, 51, 16))
        self.lblCedula.setFont(font1)
        self.lblMatricula = QLabel(self.centralwidget)
        self.lblMatricula.setObjectName(u"lblMatricula")
        self.lblMatricula.setGeometry(QRect(70, 260, 71, 16))
        self.lblMatricula.setFont(font1)
        self.lblCarrera = QLabel(self.centralwidget)
        self.lblCarrera.setObjectName(u"lblCarrera")
        self.lblCarrera.setGeometry(QRect(70, 300, 61, 16))
        self.lblCarrera.setFont(font1)
        self.lblTipoactividad = QLabel(self.centralwidget)
        self.lblTipoactividad.setObjectName(u"lblTipoactividad")
        self.lblTipoactividad.setGeometry(QRect(70, 340, 121, 16))
        self.lblTipoactividad.setFont(font1)
        self.lblFecha = QLabel(self.centralwidget)
        self.lblFecha.setObjectName(u"lblFecha")
        self.lblFecha.setGeometry(QRect(70, 190, 51, 16))
        self.lblFecha.setFont(font1)
        self.dtFecha = QDateEdit(self.centralwidget)
        self.dtFecha.setObjectName(u"dtFecha")
        self.dtFecha.setGeometry(QRect(130, 190, 110, 22))
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(130, 120, 211, 20))
        self.txtNombre.setMaxLength(250)
        self.txtCedula = QLineEdit(self.centralwidget)
        self.txtCedula.setObjectName(u"txtCedula")
        self.txtCedula.setGeometry(QRect(130, 160, 121, 20))
        self.txtCedula.setMaxLength(10)
        self.txtMatricula = QLineEdit(self.centralwidget)
        self.txtMatricula.setObjectName(u"txtMatricula")
        self.txtMatricula.setGeometry(QRect(140, 260, 161, 20))
        self.txtMatricula.setMaxLength(9)
        self.txtMatricula.setReadOnly(False)
        self.txtCarrera = QLineEdit(self.centralwidget)
        self.txtCarrera.setObjectName(u"txtCarrera")
        self.txtCarrera.setGeometry(QRect(130, 300, 271, 20))
        self.txtCarrera.setMaxLength(250)
        self.cbTipoactividad = QComboBox(self.centralwidget)
        self.cbTipoactividad.addItem("")
        self.cbTipoactividad.addItem("")
        self.cbTipoactividad.addItem("")
        self.cbTipoactividad.addItem("")
        self.cbTipoactividad.setObjectName(u"cbTipoactividad")
        self.cbTipoactividad.setGeometry(QRect(190, 340, 321, 22))
        self.btnGuardar = QPushButton(self.centralwidget)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setGeometry(QRect(210, 400, 75, 23))
        self.btnLimpiar = QPushButton(self.centralwidget)
        self.btnLimpiar.setObjectName(u"btnLimpiar")
        self.btnLimpiar.setGeometry(QRect(320, 400, 75, 23))
        self.btnActualizar = QPushButton(self.centralwidget)
        self.btnActualizar.setObjectName(u"btnActualizar")
        self.btnActualizar.setGeometry(QRect(260, 460, 75, 23))
        self.btnEliminar = QPushButton(self.centralwidget)
        self.btnEliminar.setObjectName(u"btnEliminar")
        self.btnEliminar.setGeometry(QRect(480, 90, 75, 23))
        self.lblBuscar = QLabel(self.centralwidget)
        self.lblBuscar.setObjectName(u"lblBuscar")
        self.lblBuscar.setGeometry(QRect(70, 60, 201, 21))
        self.lblBuscar.setFont(font1)
        self.txtBuscar = QLineEdit(self.centralwidget)
        self.txtBuscar.setObjectName(u"txtBuscar")
        self.txtBuscar.setGeometry(QRect(270, 60, 211, 20))
        self.txtBuscar.setMaxLength(10)
        self.btnBuscar = QPushButton(self.centralwidget)
        self.btnBuscar.setObjectName(u"btnBuscar")
        self.btnBuscar.setGeometry(QRect(490, 50, 51, 31))
        self.lblDuracion = QLabel(self.centralwidget)
        self.lblDuracion.setObjectName(u"lblDuracion")
        self.lblDuracion.setGeometry(QRect(70, 230, 141, 21))
        self.lblDuracion.setFont(font1)
        self.txtDuracion = QLineEdit(self.centralwidget)
        self.txtDuracion.setObjectName(u"txtDuracion")
        self.txtDuracion.setGeometry(QRect(220, 230, 161, 20))
        self.txtDuracion.setMaxLength(20)
        vtnSistemaActividad.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(vtnSistemaActividad)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 609, 22))
        vtnSistemaActividad.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(vtnSistemaActividad)
        self.statusbar.setObjectName(u"statusbar")
        vtnSistemaActividad.setStatusBar(self.statusbar)

        self.retranslateUi(vtnSistemaActividad)

        QMetaObject.connectSlotsByName(vtnSistemaActividad)
    # setupUi

    def retranslateUi(self, vtnSistemaActividad):
        vtnSistemaActividad.setWindowTitle(QCoreApplication.translate("vtnSistemaActividad", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("vtnSistemaActividad", u"Sistema Actividades de  Estudiantes", None))
        self.lblNombre.setText(QCoreApplication.translate("vtnSistemaActividad", u"Nombre:", None))
        self.lblCedula.setText(QCoreApplication.translate("vtnSistemaActividad", u"Cedula:", None))
        self.lblMatricula.setText(QCoreApplication.translate("vtnSistemaActividad", u"Matricula:", None))
        self.lblCarrera.setText(QCoreApplication.translate("vtnSistemaActividad", u"Carrera:", None))
        self.lblTipoactividad.setText(QCoreApplication.translate("vtnSistemaActividad", u"Tipo de actividad:", None))
        self.lblFecha.setText(QCoreApplication.translate("vtnSistemaActividad", u"Fecha:", None))
        self.txtMatricula.setInputMask("")
        self.txtMatricula.setText("")
        self.txtMatricula.setPlaceholderText(QCoreApplication.translate("vtnSistemaActividad", u"ej. 1111-1111", None))
        self.cbTipoactividad.setItemText(0, QCoreApplication.translate("vtnSistemaActividad", u"Seleccionar", None))
        self.cbTipoactividad.setItemText(1, QCoreApplication.translate("vtnSistemaActividad", u"Deportiva", None))
        self.cbTipoactividad.setItemText(2, QCoreApplication.translate("vtnSistemaActividad", u"Cultural", None))
        self.cbTipoactividad.setItemText(3, QCoreApplication.translate("vtnSistemaActividad", u"Academica con atributos adicionales", None))

        self.btnGuardar.setText(QCoreApplication.translate("vtnSistemaActividad", u"Guardar", None))
        self.btnLimpiar.setText(QCoreApplication.translate("vtnSistemaActividad", u"Limpiar", None))
        self.btnActualizar.setText(QCoreApplication.translate("vtnSistemaActividad", u"Actualizar", None))
        self.btnEliminar.setText(QCoreApplication.translate("vtnSistemaActividad", u"Eliminar", None))
        self.lblBuscar.setText(QCoreApplication.translate("vtnSistemaActividad", u"Buscar estudiante por cedula:", None))
        self.btnBuscar.setText(QCoreApplication.translate("vtnSistemaActividad", u"Buscar", None))
        self.lblDuracion.setText(QCoreApplication.translate("vtnSistemaActividad", u"Duracion de actividad:", None))
        self.txtDuracion.setPlaceholderText(QCoreApplication.translate("vtnSistemaActividad", u"formato Hrs. \"0.00\" hrs", None))
    # retranslateUi

